/* Generated from styles/_vars.scss */

export const
    FONT_FAM_TITLE_SRC: string = 'url(https://fonts.gstatic.com/s/neuton/v24/UMBQrPtMoH62xUZKAKkvcwr4Pro.woff2)',
    FONT_FAM_TITLE: string = 'Neuton',
    FONT_FAM_BODY: string = 'Roboto, san-serif',
    FONT_SIZE_BASE: number = 16,
    FONT_SIZE_H1: number = 72,
    FONT_SIZE_H2: number = 52,
    FONT_SIZE_H3: number = 40,
    FONT_SIZE_H4: number = 28,
    FONT_SIZE_BL: number = 20,
    FONT_SIZE_BM: number = 18,
    FONT_SIZE_BS: number = 14,
    COLOR_BG_D: string = '#111111',
    COLOR_BG_L: string = '#111128',
    COLOR_BG_LL: string = 'rgba(255, 255, 255, 0.9333333333)',
    COLOR_TEXT_L: string = '#ffffff',
    COLOR_TEXT_D: string = '#111128',
    COLOR_TEXT_SHADOW: string = 'rgba(17, 17, 17, 0.5333333333)',
    COLOR_TEXT_LINK: string = '#4848c8',
    Z_CANVAS_BG: number = 0,
    Z_CANVAS_FG: number = 10,
    Z_BUTTONS: number = 20,
    Z_PAGE: number = 30,
    ANI_SH: number = 500,
    ANI_LG: number = 1000,
    CLASS_CAN_SEA_LOWER: string = 'canvas__sea--lower',
    CLASS_SECTION_OPEN: string = 'section--open';