const
    FS = require('fs'),
    sharp = require('sharp'),
    { createCanvas, loadImage } = require('canvas');

const
    DIR_FROM = 'images',
    DIR_TO = 'dist/assets',
    DIR_STYLE_VARS = 'styles/_vars.scss',
    PATH_TO_TS = 'scripts/data/images.json.ts',
    WIDTH_XS = getStyleVarPxValue('w-img-xs'),
    WIDTH_SM = getStyleVarPxValue('w-img-sm'),
    WIDTH_MD = getStyleVarPxValue('w-img-md'),
    CAN_XS = createCanvas(WIDTH_XS, WIDTH_XS),
    CAN_SM = createCanvas(WIDTH_SM, WIDTH_SM),
    CTX_XS = CAN_XS.getContext('2d'),
    CTX_SM = CAN_SM.getContext('2d');

CTX_SM.imageSmoothingEnabled = false;


//
// Get requried image sizes from SCSS vars file
//

function getStyleVarPxValue(name) {
    return parseInt(
        FS
            .readFileSync(DIR_STYLE_VARS)
            .toString('utf8')
            .match(new RegExp(name + '\\s*:\\s*([0-9]+)px'))[1]
    );
}


//
// Resizes all images to medium width squares for faster loading
//

FS.readdir(DIR_FROM, (_, files) => {
    files
        .filter(f => f.match(/\.png$/))
        .forEach(f => {
            const PATH_FROM = DIR_FROM + '/' + f;
            [
                [WIDTH_SM, DIR_TO + '/' + f.replace('.png', '.sm.png')],
                [WIDTH_MD, DIR_TO + '/' + f.replace('.png', '.md.png')]
            ].forEach(size => {
                sharp(PATH_FROM)
                    .resize(size[0], size[0], {
                        kernel: sharp.kernel.mks2021,
                        fit: 'cover',
                        position: 'center'
                    })
                    .toFile(size[1]);
            });
        });
});


//
// Extracts a WIDTH_SM*WIDTH_SM version of each project image to be used as a micro-preview by cublets,
// without the need for client to load full image
//

FS.readdir(DIR_FROM, (_, files) => {
    const FILES = files.filter(f => f.match(/\.png$/));

    parseImages(FILES)
        .then((data) => FS.writeFile(
            PATH_TO_TS,
                `/* Generated by "build-scripts/prep-images.js" from "${ DIR_FROM }/*.png" */\n\n` +
                `export const DATA: { [name: string]: number[] } = {\n${
                    data
                        .map(d => `\t"${ d[0] }": [${ d[1].join(',') }]`)
                        .join(',\n')
                }\n};\n\n` +
                `export const DATA_BG: { [name: string]: string } = {\n${
                    data
                        .map(d => `\t"${ d[0] }": "#${
                            d[2]
                                .map(c => Math.floor(c * (16**2 / 256)).toString(16).padStart(2, '0'))
                                .join('')
                        }"`)
                        .join(',\n')
                }\n};\n`,
            'utf8',
            () => {}
        ));
});

async function parseImages(files) {
    const DATA = [];
    for (let i = 0; i < files.length; i++) {
        const
            FILE = files[i],
            IMG = await loadImage(DIR_FROM + '/' + FILE);

        CTX_XS.drawImage(IMG, 0, 0, WIDTH_XS, WIDTH_XS);
        CTX_SM.drawImage(IMG, 0, 0, WIDTH_SM, WIDTH_SM);
        
        const
            IMG_DATA_XS = CTX_XS.getImageData(0, 0, WIDTH_XS, WIDTH_XS)
                .data
                .filter((_, i) => i % 4 !== 3),
            IMG_DATA_SM = CTX_SM.getImageData(0, 0, WIDTH_SM, WIDTH_SM)
                .data
                .filter((_, i) => i % 4 !== 3),
            BG = {};

        // Get most common edge color to use as background
        for (let y = 0; y < WIDTH_SM; y++) {
            for (let x = 0; x < WIDTH_SM; x++) {
                if (y === 0 || y === WIDTH_SM - 1 || x === 0 || x === WIDTH_SM - 1) {
                    const
                        I = ((y * WIDTH_SM) + x) * 3,
                        C = [
                            IMG_DATA_SM[I],
                            IMG_DATA_SM[I + 1],
                            IMG_DATA_SM[I + 2]
                        ].join();
                    BG[C] = BG[C] ? BG[C] + 1 : 1;
                }
            }
        }
        DATA.push([
            FILE.replace(/\.png/, ''),
            IMG_DATA_XS,
            Object
                .entries(BG)
                .sort((a, b) => b[1] - a[1])[0][0]
                .split(',')
        ]);
    }
    return DATA;
}