const
    FS = require('fs'),
    SASS = require('sass'),
    sharp = require('sharp'),
    { createCanvas, loadImage } = require('canvas');


//
// Extracts a Q*Q version of each project image to be used as a micro-preview by cublets,
// without the need for client to load full image
//

const
    DIR_FROM = 'dist/images',
    PATH_TO_TS = 'scripts/graphics/cublet-pixels.json.ts',
    Q = 7,
    CAN = createCanvas(Q, Q),
    CTX = CAN.getContext('2d');

CTX.imageSmoothingEnabled = false;

FS.readdir(DIR_FROM, (_, files) => {
    const FILES = files.filter(f => f.match(/\.png$/));

    parseImages(FILES)
        .then((data) => FS.writeFile(
            PATH_TO_TS,
                `/* Generated by "build-scripts/prep-images.js" from "${PATH_TO_TS}/*.png" */\n\n` +
                `export const DATA: { [name: string]: number[] } = {\n${
                    data
                        .map(d => `\t"${ d[0] }": [${
                            d[1]
                                .filter((_, i) => i % 4 !== 3)
                                .join(',')
                        }]`)
                        .join(',\n')
                }\n};`,
            'utf8',
            () => {}
        ));
});

async function parseImages(files) {
    const DATA = [];
    for (let i = 0; i < files.length; i++) {
        const
            FILE = files[i],
            IMG = await loadImage(DIR_FROM + '/' + FILE);
        CTX.drawImage(IMG, 0, 0, Q, Q);
        DATA.push([
            FILE.replace(/\.png/, ''),
            CTX.getImageData(0, 0, Q, Q).data
        ]);
    }
    return DATA;
}


//
// Resizes all images to smaller width squares for faster loading
//

const WIDTH_SM = 200;

FS.readdir(DIR_FROM, (_, files) => {
    files
        .filter(f => f.match(/\.png$/) && !f.match(/\.sm\.png$/))
        .forEach(f => {
            const
                PATH = DIR_FROM + '/' + f;
                PATH_SM = PATH.replace('.png', '.sm.png');
            sharp(PATH)
                .resize(WIDTH_SM, WIDTH_SM, {
                    kernel: sharp.kernel.mks2021,
                    fit: 'cover',
                    position: 'center'
                })
                .toFile(PATH_SM)
        });
});