const
    FS = require('fs'),
    SASS = require('sass'),
    sharp = require('sharp'),
    { createCanvas, loadImage } = require('canvas');


//
// Extracts a Q*Q version of each project image to be used as a micro-preview by cublets,
// without the need for client to load full image
//

const
    DIR_FROM = 'images',
    DIR_TO = 'dist/assets',
    PATH_TO_TS = 'scripts/graphics/cublet-pixels.json.ts',
    Q = 12,
    CAN = createCanvas(Q, Q),
    CTX = CAN.getContext('2d');

CTX.imageSmoothingEnabled = false;

FS.readdir(DIR_FROM, (_, files) => {
    const FILES = files.filter(f => f.match(/\.png$/));

    parseImages(FILES)
        .then((data) => FS.writeFile(
            PATH_TO_TS,
                `/* Generated by "build-scripts/prep-images.js" from "${PATH_TO_TS}/*.png" */\n\n` +
                `export const DATA: { [name: string]: number[] } = {\n${
                    data
                        .map(d => `\t"${ d[0] }": [${ d[1].join(',') }]`)
                        .join(',\n')
                }\n}\n\n` +
                `export const DATA_BG: { [name: string]: string } = {\n${
                    data
                        .map(d => `\t"${ d[0] }": "rgb(${ d[2][0] }, ${ d[2][1] }, ${ d[2][2] })"`)
                        .join(',\n')
                }\n}\n`,
            'utf8',
            () => {}
        ));
});

async function parseImages(files) {
    const DATA = [];
    for (let i = 0; i < files.length; i++) {
        const
            FILE = files[i],
            IMG = await loadImage(DIR_FROM + '/' + FILE);
        CTX.drawImage(IMG, 0, 0, Q, Q);
        const
            IMG_DATA = CTX.getImageData(0, 0, Q, Q)
                .data
                .filter((_, i) => i % 4 !== 3),
            BG = {};

        // Get most common edge color to use as background
        for (let y = 0; y < Q; y++) {
            for (let x = 0; x < Q; x++) {
                if (y === 0 || y === Q - 1 || x === 0 || x === Q - 1) {
                    const
                        I = ((y * Q) + x) * 3,
                        C = [
                            IMG_DATA[I],
                            IMG_DATA[I + 1],
                            IMG_DATA[I + 2]
                        ].join();
                    BG[C] = BG[C] ? BG[C] + 1 : 1;
                }
            }
        }
        DATA.push([
            FILE.replace(/\.png/, ''),
            IMG_DATA,
            Object
                .entries(BG)
                .sort((a, b) => b[1] - a[1])[0][0]
                .split(',')
        ]);
    }
    return DATA;
}


//
// Resizes all images to smaller width squares for faster loading
//

const WIDTH_SM = 200;

FS.readdir(DIR_FROM, (_, files) => {
    files
        .filter(f => f.match(/\.png$/))
        .forEach(f => {
            const
                PATH_FROM = DIR_FROM + '/' + f;
                PATH_TO = DIR_TO + '/' + f.replace('.png', '.sm.png');
            sharp(PATH_FROM)
                .resize(WIDTH_SM, WIDTH_SM, {
                    kernel: sharp.kernel.mks2021,
                    fit: 'cover',
                    position: 'center'
                })
                .toFile(PATH_TO)
        });
});